#:kivy 1.4

<Catalog>:
    screen_manager: screen_manager
    orientation: 'vertical'
    BoxLayout:
        id: reactive_layout
        orientation: 'vertical' if self.width < self.height else 'horizontal'


        ScreenManager:
            id: screen_manager
            Screen:
                name: "Visible"
                RPIDContainer:
            Screen:
                name: "Hidden"
                RPIDHiddenContainer:
           
           
